version: "3"

services:
  usuario:
    container_name: ms-usuario
    build:
      context: ./MSSeguridad
    ports:
      - "8082:82"
    networks:
    - TDB

  gateway:
    build:
      context: ./Gateway
    ports:
      - "6004:6001"
    depends_on:
      - usuario

    networks:
    - TDB
networks:
  TDB:
    name: ms-unu